# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from plyer import notification
import sys


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(869, 637)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(650, 550, 92, 37))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(760, 550, 92, 37))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(310, 40, 401, 18))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 869, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuStyle = QtWidgets.QMenu(self.menubar)
        self.menuStyle.setObjectName("menuStyle")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionNew_Project = QtWidgets.QAction(MainWindow)
        self.actionNew_Project.setObjectName("actionNew_Project")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSaev_As = QtWidgets.QAction(MainWindow)
        self.actionSaev_As.setObjectName("actionSaev_As")
        self.actionImport = QtWidgets.QAction(MainWindow)
        self.actionImport.setObjectName("actionImport")
        self.actionExort = QtWidgets.QAction(MainWindow)
        self.actionExort.setObjectName("actionExort")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionInstallation = QtWidgets.QAction(MainWindow)
        self.actionInstallation.setObjectName("actionInstallation")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionThemes = QtWidgets.QAction(MainWindow)
        self.actionThemes.setObjectName("actionThemes")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionColor_Schemes = QtWidgets.QAction(MainWindow)
        self.actionColor_Schemes.setObjectName("actionColor_Schemes")
        self.actionFont_typoe = QtWidgets.QAction(MainWindow)
        self.actionFont_typoe.setObjectName("actionFont_typoe")
        self.actionFont = QtWidgets.QAction(MainWindow)
        self.actionFont.setObjectName("actionFont")
        self.actionFont_Stye = QtWidgets.QAction(MainWindow)
        self.actionFont_Stye.setObjectName("actionFont_Stye")
        self.actionZoom_in = QtWidgets.QAction(MainWindow)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtWidgets.QAction(MainWindow)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionSize = QtWidgets.QAction(MainWindow)
        self.actionSize.setObjectName("actionSize")
        self.actionEditor_Font_size = QtWidgets.QAction(MainWindow)
        self.actionEditor_Font_size.setObjectName("actionEditor_Font_size")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionNew_Project)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSaev_As)
        self.menuFile.addAction(self.actionImport)
        self.menuFile.addAction(self.actionExort)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuView.addAction(self.actionZoom_in)
        self.menuView.addAction(self.actionZoom_out)
        self.menuView.addAction(self.actionSize)
        self.menuView.addAction(self.actionEditor_Font_size)
        self.menuStyle.addAction(self.actionFont)
        self.menuStyle.addAction(self.actionFont_Stye)
        self.menuSettings.addAction(self.actionThemes)
        self.menuSettings.addAction(self.actionPreferences)
        self.menuSettings.addAction(self.actionColor_Schemes)
        self.menuHelp.addAction(self.actionInstallation)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuStyle.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def b1click(self):
        self.label.setText('Button click now')
        notification.notify(
            title="Hello",
            message="I was clicked",
            timeout=2
        )

    def closeApp(self):
        sys.exit()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Close"))
        self.pushButton_2.setText(_translate("MainWindow", "Finish"))
        self.pushButton_2.clicked.connect(self.b1click)
        self.pushButton.clicked.connect(self.closeApp)
        self.label.setText(_translate(
            "MainWindow", "This is Python3 with Qt5"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuStyle.setTitle(_translate("MainWindow", "Style"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionNew_Project.setText(
            _translate("MainWindow", "New Project..."))
        self.actionOpen.setText(_translate("MainWindow", "Open..."))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSaev_As.setText(_translate("MainWindow", "Save As.."))
        self.actionImport.setText(_translate("MainWindow", "Import.."))
        self.actionExort.setText(_translate("MainWindow", "Export..."))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionInstallation.setText(
            _translate("MainWindow", "Installation "))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionThemes.setText(_translate("MainWindow", "Themes"))
        self.actionPreferences.setText(
            _translate("MainWindow", "Preferences..."))
        self.actionColor_Schemes.setText(
            _translate("MainWindow", "Color Schemes"))
        self.actionFont_typoe.setText(_translate("MainWindow", "Font typoe"))
        self.actionFont.setText(_translate("MainWindow", "Font"))
        self.actionFont_Stye.setText(_translate("MainWindow", "Font Style"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.actionSize.setText(_translate("MainWindow", "Size"))
        self.actionEditor_Font_size.setText(
            _translate("MainWindow", "Editor Font size"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
